title: Idlir's notes
description: Random personal projects and notes
theme: just-the-docs

url: https://idlirshkurti.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
