title: Idlir's notes
description: Random personal projects and notes
theme: just-the-docs

url: https://idlirshkurti.github.io

markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_kramdown: mathjax
